kind: ConfigMap
apiVersion: v1
metadata:
  name: oe-todo-dynamic-projects-config-map
  namespace: default
  labels:
    {{- include "oe-todo-dynamic-projects-deploy.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: 9991
    spring:
      r2dbc:
        url: r2dbc:mariadb://westworld:30006/dynamic_projects
        username: root
        password: secretpassword
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: admin
        password: admin