kind: ConfigMap
apiVersion: v1
metadata:
  name: oe-todo-config-map
  namespace: default
  labels:
    {{- include "oe-todo-tasks-deploy.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: 9991
    spring:
      datasource:
        url: jdbc:mariadb://mariadb:3306/todo
        username: root
        password: dt6peaYKBE
        initialization-mode: always
      jpa:
        show-sql: true
        generate-ddl: true
        properties:
          hibernate:
            format_sql: true
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: user
        password: luVpvEEEyz9oZMsU