kind: ConfigMap
apiVersion: v1
metadata:
  name: metrics-demo-config-map
  namespace: default
  labels:
    {{- include "metrics-demo.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: 8080